### ISSUE TITLE
上传 Github 上，Github page 无样式

### ISSUE THREAD

**Issue by hacpai** [suyan/suyan.github.io#18]
Hi suyan：

在本机上运行这个主题没问题，上传 Github 后，主题样式全丢失，是哪里有设置问题呢？

我的 blog http://hacpai.github.io/simpleblog/

**Comment by suyan** [comment]
@hacpal 你把博客放在子目录下了，得把css文件的路径改一下

**Comment by hacpai** [comment]
@suyan Thank you so much.

我提了一个 PR，添加对 Github Page 的支持。

https://github.com/suyan/suyan.github.io/pull/19

**Comment by suyan** [comment]
@hacpai 多谢，我研究一下Jekyll的baseurl先，我还不确定哪些链接需要改
